Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://85.17.207.80:3000"
  copyright: Immah copyright statement
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
